### ISSUE TITLE
Wrong requirement for request_hawk

### ISSUE THREAD

**Issue by twidi** [mozilla-services/syncclient#26]
[Version 0.9.0.dev0 sha 5f5d2d9, py3.4]

I think in #24 you forgot to update the requirement of `request-hawk` in `requirements.txt`:

```python
Traceback (most recent call last):
  File "syncclient/main.py", line 27, in <module>
    main()
  File "syncclient/main.py", line 23, in main
    client = SyncClient(*bid_assertion_args)
  File "/home/twidi/dev/syncclient/syncclient/client.py", line 106, in __init__
    key=credentials['key'])
TypeError: __init__() got an unexpected keyword argument 'algorithm'
```

PS: it works with `requests-hawk==1.0.0`

**Comment by twidi** [comment]
Solved with 82a5226d78f06b9299b15a91f950a2ec6aff79e4
